package panelView;

import java.awt.Component;
import javax.swing.JOptionPane;
import exception.*;
import control.CustomerControl;
import model.Customer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class CustomerMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    private CustomerControl cc = new CustomerControl();
    private Customer c = null;
    String actionCustomer = null;
    int idCustomer = 0;
    private Component rootPane;
    
    
    private void InputKosongCustomerException() throws KosongException{
        if(namaCustomerInputTextField.getText().isEmpty() || alamatCustomerInputTextField.getText().isEmpty() || nikCustomerInputTextField.getText().isEmpty())
            throw new KosongException();
    }
    
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
            
    private void NomorTeleponCustomerException() throws NomorTeleponException{
        if(!notelpCustomerInputTextField.getText().matches("^\\+?[0-9]+$"))
            throw new NomorTeleponException();
    }
    
    public CustomerMainPanel() {
        initComponents();
        setOpaque(false);
        showCustomer();
        setComponentsCustomer(false);        
        setEditDeleteButtonCustomer(false);        
        clearTextCustomer();
    }
    
    // Customer Set Komponen
    public void setComponentsCustomer(boolean value){
        namaCustomerInputTextField.setEnabled(value);
        alamatCustomerInputTextField.setEnabled(value);
        nikCustomerInputTextField.setEnabled(value);
        notelpCustomerInputTextField.setEnabled(value);
    }
    
    // Customer Set Edit Delete Button
    public void setEditDeleteButtonCustomer(boolean value){
        editCustomerInputButton.setEnabled(value);
        deleteCustomerInputButton.setEnabled(value);
    }
    
    // Customer Clear Text
    public void clearTextCustomer(){
        namaCustomerInputTextField.setText("");
        alamatCustomerInputTextField.setText("");
        nikCustomerInputTextField.setText("");
        notelpCustomerInputTextField.setText("");
        searchCustomerInputTextField.setText("");
    }
    
    public void showCustomer(){
//        customerTextArea.setText("Daftar Customer: \n ============= \n"+cc.showData()); 
    }

    private void doSearchCustomer(){
        if(searchCustomerInputTextField.getText().isEmpty())
            return;
            Customer c = cc.search(Integer.parseInt(searchCustomerInputTextField.getText()));
            if(c == null ){
                JOptionPane.showMessageDialog(rootPane, "Customer Tidak Ditemukan");
                return;
            }
            setEditDeleteButtonCustomer(true);
            clearTextCustomer();
            
            namaCustomerInputTextField.setText(c.getNama());
            alamatCustomerInputTextField.setText(c.getAlamat());
            nikCustomerInputTextField.setText(c.getNik());
            notelpCustomerInputTextField.setText(c.getNo_telepon());
            
            idCustomer = c.getId_customer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchCustomerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        searchCustomerInputTextField = new javax.swing.JTextField();
        searchCustomerButton = new javax.swing.JButton();
        formCustomerInputPanel = new javax.swing.JPanel();
        namaCustomerInputTextField = new javax.swing.JTextField();
        namaCustomerInputLabel = new javax.swing.JLabel();
        nikCustomerInputLabel = new javax.swing.JLabel();
        nikCustomerInputTextField = new javax.swing.JTextField();
        alamatCustomerInputLabel = new javax.swing.JLabel();
        alamatCustomerInputTextField = new javax.swing.JTextField();
        actionButtonCustomerPanel = new javax.swing.JPanel();
        addCustomerInputButton = new javax.swing.JButton();
        deleteCustomerInputButton = new javax.swing.JButton();
        editCustomerInputButton = new javax.swing.JButton();
        saveCustomerButton = new javax.swing.JButton();
        notelpCustomerInputLabel = new javax.swing.JLabel();
        notelpCustomerInputTextField = new javax.swing.JTextField();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTextArea = new javax.swing.JTextArea();

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchCustomerPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        customerLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("CUSTOMER");

        searchCustomerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchCustomerInputTextFieldKeyTyped(evt);
            }
        });

        searchCustomerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchCustomerButton.setText("Search");
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(customerLabel))
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchCustomerButton)
                .addGap(172, 172, 172))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerLabel))
                    .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchCustomerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formCustomerInputPanel.setOpaque(false);

        namaCustomerInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        namaCustomerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaCustomerInputLabel.setText("Nama ");

        nikCustomerInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        nikCustomerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        nikCustomerInputLabel.setText("NIK ");

        alamatCustomerInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        alamatCustomerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        alamatCustomerInputLabel.setText("Alamat");

        actionButtonCustomerPanel.setOpaque(false);

        addCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addCustomerInputButton.setText("ADD");
        addCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerInputButtonActionPerformed(evt);
            }
        });

        deleteCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        deleteCustomerInputButton.setText("DELETE");
        deleteCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerInputButtonActionPerformed(evt);
            }
        });

        editCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        editCustomerInputButton.setText("EDIT");
        editCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionButtonCustomerPanelLayout = new javax.swing.GroupLayout(actionButtonCustomerPanel);
        actionButtonCustomerPanel.setLayout(actionButtonCustomerPanelLayout);
        actionButtonCustomerPanelLayout.setHorizontalGroup(
            actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCustomerInputButton)
                .addGap(33, 33, 33)
                .addComponent(editCustomerInputButton)
                .addGap(31, 31, 31)
                .addComponent(deleteCustomerInputButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        actionButtonCustomerPanelLayout.setVerticalGroup(
            actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonCustomerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(editCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        saveCustomerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveCustomerButton.setText("SAVE");
        saveCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerButtonActionPerformed(evt);
            }
        });

        notelpCustomerInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        notelpCustomerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        notelpCustomerInputLabel.setText("Nomor Telepon");

        javax.swing.GroupLayout formCustomerInputPanelLayout = new javax.swing.GroupLayout(formCustomerInputPanel);
        formCustomerInputPanel.setLayout(formCustomerInputPanelLayout);
        formCustomerInputPanelLayout.setHorizontalGroup(
            formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaCustomerInputLabel)
                    .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nikCustomerInputLabel)
                    .addComponent(nikCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatCustomerInputLabel)
                            .addComponent(alamatCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(actionButtonCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notelpCustomerInputLabel)
                            .addComponent(notelpCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveCustomerButton)
                        .addGap(273, 273, 273))))
        );
        formCustomerInputPanelLayout.setVerticalGroup(
            formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(actionButtonCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nikCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                                .addComponent(namaCustomerInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                                .addComponent(alamatCustomerInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alamatCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nikCustomerInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCustomerInputPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notelpCustomerInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notelpCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        customerScrollPane.setOpaque(false);

        customerTextArea.setColumns(20);
        customerTextArea.setRows(5);
        customerScrollPane.setViewportView(customerTextArea);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustomerInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerInputTextFieldKeyTyped
        if(evt.getKeyChar()=='\n'){
            doSearchCustomer();
        }
    }//GEN-LAST:event_searchCustomerInputTextFieldKeyTyped

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        doSearchCustomer();
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    private void addCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerInputButtonActionPerformed
        actionCustomer = "Tambah";
        clearTextCustomer();
        setEditDeleteButtonCustomer(true);
        setComponentsCustomer(true);
    }//GEN-LAST:event_addCustomerInputButtonActionPerformed

    private void editCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerInputButtonActionPerformed
        actionCustomer = "Edit";
        setComponentsCustomer(true);
    }//GEN-LAST:event_editCustomerInputButtonActionPerformed

    private void deleteCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerInputButtonActionPerformed
        clearTextCustomer();
        setEditDeleteButtonCustomer(false);
        setComponentsCustomer(false);
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Melakukan Hapus?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idCustomer = -1;
            return;
        }
        
        cc.delete(idCustomer);
        idCustomer = -1;
        showCustomer();
    }//GEN-LAST:event_deleteCustomerInputButtonActionPerformed

    private void saveCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerButtonActionPerformed
        if(actionCustomer == null)
            return;
        try{
            InputKosongCustomerException();
            NomorTeleponCustomerException();
            int result = JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Yakin Ingin Melakukan " + actionCustomer + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (result != JOptionPane.YES_OPTION) {
                return;
            }
            
            switch(actionCustomer){
            case "Tambah":
                c = new Customer(namaCustomerInputTextField.getText(), notelpCustomerInputTextField.getText(), alamatCustomerInputTextField.getText(), nikCustomerInputTextField.getText());
                cc.insert(c);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
            case "Edit":
                c = new Customer(namaCustomerInputTextField.getText(), notelpCustomerInputTextField.getText(), alamatCustomerInputTextField.getText(), nikCustomerInputTextField.getText());
                cc.update(c, idCustomer);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
            default:
                break;
        }
        showCustomer();
        actionCustomer = null;
        }catch(KosongException e){
            System.err.println(e);
        }catch(NomorTeleponException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        };
    }//GEN-LAST:event_saveCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonCustomerPanel;
    private javax.swing.JButton addCustomerInputButton;
    private javax.swing.JLabel alamatCustomerInputLabel;
    private javax.swing.JTextField alamatCustomerInputTextField;
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTextArea customerTextArea;
    private javax.swing.JButton deleteCustomerInputButton;
    private javax.swing.JButton editCustomerInputButton;
    private javax.swing.JPanel formCustomerInputPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaCustomerInputLabel;
    private javax.swing.JTextField namaCustomerInputTextField;
    private javax.swing.JLabel nikCustomerInputLabel;
    private javax.swing.JTextField nikCustomerInputTextField;
    private javax.swing.JLabel notelpCustomerInputLabel;
    private javax.swing.JTextField notelpCustomerInputTextField;
    private javax.swing.JButton saveCustomerButton;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JTextField searchCustomerInputTextField;
    private javax.swing.JPanel searchCustomerPanel;
    // End of variables declaration//GEN-END:variables
}
