package panelView;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import exception.*;
import control.FilmControl;
import control.CategoryControl;
import model.Film;
import model.Category;
import java.util.List;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class FilmMainPanel extends javax.swing.JPanel {

    private FilmControl fc = new FilmControl();
    private CategoryControl cc = new CategoryControl();
    private Film f = null;
    String actionFilm = null;
    int idFilm = 0;
    private Component rootPane;
    List<Category> listCategory;


    public FilmMainPanel() {
        initComponents();
        setOpaque(false);
        showFilm();
        setComponentsFilm(false);
        setFilmEditDeleteButton(false);
        clearText(); 
    }
    
    public void InputKosongFilmException() throws KosongException{
        if(idFilmInputTextField.getText().isEmpty() || tahunFilmRilisInputTextField.getText().isEmpty())
            throw new KosongException();
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void setFilmToDropdown(){
        listCategory = cc.showData();
        System.out.println(listCategory.size());
        for(int i = 0; i < listCategory.size(); i++){
            kategoriFilmDropdown.addItem(listCategory.get(i));
        }
    }
    
    public void setComponentsFilm(boolean value){
        idFilmInputTextField.setEnabled(value);
        judulFilmInputTextField.setEnabled(value);
        tahunFilmRilisInputTextField.setEnabled(value);
        kategoriFilmDropdown.setEnabled(value);
    }
    
    public void setFilmEditDeleteButton(boolean value){
        editFilmInputButton.setEnabled(value);
        deleteFilmInputButton.setEnabled(value);
    }
    
    public void clearText(){
        idFilmInputTextField.setText("");
        judulFilmInputTextField.setText("");
        tahunFilmRilisInputTextField.setText("");
        kategoriFilmDropdown.setSelectedIndex(-1);
        searchFilmInputTextField.setText("");
    }
    
    public void showFilm(){
        String target = searchFilmInputTextField.getText();
        List<Film> daftarFilm = fc.showData(target);

//        filmTextArea.setText("Daftar Film: \n ============= \n" + fc.showData());
    }
    
    private void doSearchFilm(){
        int idCategory = Integer.parseInt(searchFilmInputTextField.getText());
        if(searchFilmInputTextField.getText().isEmpty())
            return;
        
            f = fc.search(idCategory);
            
        if(f != null){
            setFilmEditDeleteButton(true);
            idFilmInputTextField.setText(Integer.toString(f.getId_film()));
            judulFilmInputTextField.setText(f.getJudul());
            tahunFilmRilisInputTextField.setText(f.getTahun_rilis());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Film Tidak Ditemukan!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchFilmPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        filmLabel = new javax.swing.JLabel();
        searchFilmInputTextField = new javax.swing.JTextField();
        searchFilmButton = new javax.swing.JButton();
        formFilmInputPanel = new javax.swing.JPanel();
        idFilmInputTextField = new javax.swing.JTextField();
        idFilmInputLabel = new javax.swing.JLabel();
        kategoriFilmInputLabel = new javax.swing.JLabel();
        tahunRilisFilmInputLabel = new javax.swing.JLabel();
        tahunFilmRilisInputTextField = new javax.swing.JTextField();
        actionButtonFilmPanel = new javax.swing.JPanel();
        addFilmInputButton = new javax.swing.JButton();
        deleteFilmInputButton = new javax.swing.JButton();
        editFilmInputButton = new javax.swing.JButton();
        saveFilmButton = new javax.swing.JButton();
        kategoriFilmDropdown = new javax.swing.JComboBox<>();
        judulFilmInputTextField = new javax.swing.JTextField();
        judulFilmInputLabel = new javax.swing.JLabel();
        filmScrollPane = new javax.swing.JScrollPane();
        filmTextArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1246, 708));

        mainPanel.setPreferredSize(new java.awt.Dimension(1246, 708));

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchFilmPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        filmLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        filmLabel.setForeground(new java.awt.Color(255, 255, 255));
        filmLabel.setText("FILM");

        searchFilmInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFilmInputTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFilmInputTextFieldKeyTyped(evt);
            }
        });

        searchFilmButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchFilmButton.setText("Search");
        searchFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFilmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchFilmPanelLayout = new javax.swing.GroupLayout(searchFilmPanel);
        searchFilmPanel.setLayout(searchFilmPanelLayout);
        searchFilmPanelLayout.setHorizontalGroup(
            searchFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFilmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(searchFilmInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchFilmButton)
                .addGap(172, 172, 172))
            .addGroup(searchFilmPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(filmLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchFilmPanelLayout.setVerticalGroup(
            searchFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFilmPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchFilmButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(searchFilmInputTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filmLabel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formFilmInputPanel.setOpaque(false);

        idFilmInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        idFilmInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        idFilmInputLabel.setText("ID Film");

        kategoriFilmInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        kategoriFilmInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        kategoriFilmInputLabel.setText("Genre");

        tahunRilisFilmInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tahunRilisFilmInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        tahunRilisFilmInputLabel.setText("Tahun Rilis");

        tahunFilmRilisInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tahunFilmRilisInputTextFieldKeyTyped(evt);
            }
        });

        actionButtonFilmPanel.setOpaque(false);

        addFilmInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addFilmInputButton.setText("ADD");
        addFilmInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilmInputButtonActionPerformed(evt);
            }
        });

        deleteFilmInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        deleteFilmInputButton.setText("DELETE");
        deleteFilmInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFilmInputButtonActionPerformed(evt);
            }
        });

        editFilmInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        editFilmInputButton.setText("EDIT");
        editFilmInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFilmInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionButtonFilmPanelLayout = new javax.swing.GroupLayout(actionButtonFilmPanel);
        actionButtonFilmPanel.setLayout(actionButtonFilmPanelLayout);
        actionButtonFilmPanelLayout.setHorizontalGroup(
            actionButtonFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonFilmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addFilmInputButton)
                .addGap(33, 33, 33)
                .addComponent(editFilmInputButton)
                .addGap(31, 31, 31)
                .addComponent(deleteFilmInputButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        actionButtonFilmPanelLayout.setVerticalGroup(
            actionButtonFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonFilmPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actionButtonFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addFilmInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(editFilmInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteFilmInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        saveFilmButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveFilmButton.setText("SAVE");
        saveFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFilmButtonActionPerformed(evt);
            }
        });

        judulFilmInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        judulFilmInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        judulFilmInputLabel.setText("Judul");

        javax.swing.GroupLayout formFilmInputPanelLayout = new javax.swing.GroupLayout(formFilmInputPanel);
        formFilmInputPanel.setLayout(formFilmInputPanelLayout);
        formFilmInputPanelLayout.setHorizontalGroup(
            formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kategoriFilmDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idFilmInputLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idFilmInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addComponent(kategoriFilmInputLabel))
                .addGap(31, 31, 31)
                .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addComponent(tahunRilisFilmInputLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(judulFilmInputLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulFilmInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actionButtonFilmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addComponent(tahunFilmRilisInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveFilmButton)
                        .addGap(273, 273, 273))))
        );
        formFilmInputPanelLayout.setVerticalGroup(
            formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                            .addComponent(idFilmInputLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idFilmInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formFilmInputPanelLayout.createSequentialGroup()
                            .addComponent(actionButtonFilmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addComponent(judulFilmInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judulFilmInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tahunRilisFilmInputLabel)
                    .addComponent(kategoriFilmInputLabel))
                .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(saveFilmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formFilmInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formFilmInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategoriFilmDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahunFilmRilisInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        filmScrollPane.setOpaque(false);

        filmTextArea.setColumns(20);
        filmTextArea.setRows(5);
        filmScrollPane.setViewportView(filmTextArea);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchFilmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formFilmInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filmScrollPane)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchFilmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formFilmInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filmScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFilmInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFilmInputTextFieldKeyPressed
        if(evt.getKeyChar()=='\n'){
            doSearchFilm();
        }
    }//GEN-LAST:event_searchFilmInputTextFieldKeyPressed

    private void searchFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFilmButtonActionPerformed
        doSearchFilm();
    }//GEN-LAST:event_searchFilmButtonActionPerformed

    private void addFilmInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilmInputButtonActionPerformed
        actionFilm = "Tambah";
        clearText();
        setFilmEditDeleteButton(false);
        setComponentsFilm(true);
        setFilmEditDeleteButton(false);
        
        idFilmInputTextField.setEnabled(false);
        idFilmInputTextField.setText(fc.generateId());
    }//GEN-LAST:event_addFilmInputButtonActionPerformed

    private void editFilmInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFilmInputButtonActionPerformed
        actionFilm = "Ubah";
        setComponentsFilm(true);
        idFilmInputTextField.setEnabled(false);
    }//GEN-LAST:event_editFilmInputButtonActionPerformed

    private void deleteFilmInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFilmInputButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION)
            return;
        
        int idFilm = Integer.parseInt(idFilmInputTextField.getText());
        fc.delete(idFilm);
        clearText();
        setFilmEditDeleteButton(false);
        setComponentsFilm(false);
        showFilm();
    }//GEN-LAST:event_deleteFilmInputButtonActionPerformed

    private void saveFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFilmButtonActionPerformed
        if(actionFilm == null)
            return;
        try{
            InputKosongFilmException();
            
            int result = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Melakukan " + actionFilm + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (result != JOptionPane.YES_OPTION) {
                return;
            }
            switch (actionFilm){
                case "Tambah":
                    f = new Film(judulFilmInputTextField.getText(), tahunFilmRilisInputTextField.getText(), kategoriFilmDropdown.getSelectedIndex());
                    fc.insert(f);
                    clearText();
                    setFilmEditDeleteButton(false);
                    setComponentsFilm(false);
                    showFilm();
                    break;
                    
                case "Ubah":
                    f = new Film(judulFilmInputTextField.getText(), tahunFilmRilisInputTextField.getText(), kategoriFilmDropdown.getSelectedIndex());
                    fc.update(f, kategoriFilmDropdown.getSelectedIndex());
                    clearText();
                    setFilmEditDeleteButton(false);
                    setComponentsFilm(false);
                    showFilm();
                    break;
                default:
                    break;
            }
            actionFilm = null;
        }catch(KosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }
    }//GEN-LAST:event_saveFilmButtonActionPerformed

    private void tahunFilmRilisInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunFilmRilisInputTextFieldKeyTyped
        char key = evt.getKeyChar();
        if(!Character.isDigit(key) || key == '.'){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Input Harus Berupa Angka!", "Input Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tahunFilmRilisInputTextFieldKeyTyped

    private void searchFilmInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFilmInputTextFieldKeyTyped
        if(evt.getKeyChar() == '\n'){
            doSearchFilm();
        }
    }//GEN-LAST:event_searchFilmInputTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonFilmPanel;
    private javax.swing.JButton addFilmInputButton;
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JButton deleteFilmInputButton;
    private javax.swing.JButton editFilmInputButton;
    private javax.swing.JLabel filmLabel;
    private javax.swing.JScrollPane filmScrollPane;
    private javax.swing.JTextArea filmTextArea;
    private javax.swing.JPanel formFilmInputPanel;
    private javax.swing.JLabel idFilmInputLabel;
    private javax.swing.JTextField idFilmInputTextField;
    private javax.swing.JLabel judulFilmInputLabel;
    private javax.swing.JTextField judulFilmInputTextField;
    private javax.swing.JComboBox<model.Category> kategoriFilmDropdown;
    private javax.swing.JLabel kategoriFilmInputLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveFilmButton;
    private javax.swing.JButton searchFilmButton;
    private javax.swing.JTextField searchFilmInputTextField;
    private javax.swing.JPanel searchFilmPanel;
    private javax.swing.JTextField tahunFilmRilisInputTextField;
    private javax.swing.JLabel tahunRilisFilmInputLabel;
    // End of variables declaration//GEN-END:variables
}
