package panelView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class LaporanMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public LaporanMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchCustomerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        searchCustomerInputTextField = new javax.swing.JTextField();
        searchCustomerButton = new javax.swing.JButton();
        formCustomerInputPanel = new javax.swing.JPanel();
        namaCustomerInputTextField = new javax.swing.JTextField();
        namaCustomerInputLabel = new javax.swing.JLabel();
        namaCustomerInputLabel1 = new javax.swing.JLabel();
        namaCustomerInputTextField1 = new javax.swing.JTextField();
        namaCustomerInputLabel2 = new javax.swing.JLabel();
        namaCustomerInputTextField2 = new javax.swing.JTextField();
        actionButtonCustomerPanel = new javax.swing.JPanel();
        addCustomerInputButton = new javax.swing.JButton();
        deleteCustomerInputButton = new javax.swing.JButton();
        editCustomerInputButton = new javax.swing.JButton();
        saveCustomerButton = new javax.swing.JButton();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTextArea = new javax.swing.JTextArea();

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchCustomerPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        customerLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("CUSTOMER");

        searchCustomerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchCustomerButton.setText("Search");

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(customerLabel))
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchCustomerButton)
                .addGap(172, 172, 172))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerLabel))
                    .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchCustomerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formCustomerInputPanel.setOpaque(false);

        namaCustomerInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        namaCustomerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaCustomerInputLabel.setText("Nama ");

        namaCustomerInputLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        namaCustomerInputLabel1.setForeground(new java.awt.Color(255, 255, 255));
        namaCustomerInputLabel1.setText("NIK ");

        namaCustomerInputLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        namaCustomerInputLabel2.setForeground(new java.awt.Color(255, 255, 255));
        namaCustomerInputLabel2.setText("Alamat");

        actionButtonCustomerPanel.setOpaque(false);

        addCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addCustomerInputButton.setText("ADD");

        deleteCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        deleteCustomerInputButton.setText("DELETE");

        editCustomerInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        editCustomerInputButton.setText("EDIT");

        javax.swing.GroupLayout actionButtonCustomerPanelLayout = new javax.swing.GroupLayout(actionButtonCustomerPanel);
        actionButtonCustomerPanel.setLayout(actionButtonCustomerPanelLayout);
        actionButtonCustomerPanelLayout.setHorizontalGroup(
            actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCustomerInputButton)
                .addGap(33, 33, 33)
                .addComponent(editCustomerInputButton)
                .addGap(31, 31, 31)
                .addComponent(deleteCustomerInputButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        actionButtonCustomerPanelLayout.setVerticalGroup(
            actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonCustomerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actionButtonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(editCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        saveCustomerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveCustomerButton.setText("SAVE");

        javax.swing.GroupLayout formCustomerInputPanelLayout = new javax.swing.GroupLayout(formCustomerInputPanel);
        formCustomerInputPanel.setLayout(formCustomerInputPanelLayout);
        formCustomerInputPanelLayout.setHorizontalGroup(
            formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(namaCustomerInputLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaCustomerInputLabel)
                            .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaCustomerInputLabel2)
                            .addComponent(namaCustomerInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(actionButtonCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(namaCustomerInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveCustomerButton)
                        .addGap(273, 273, 273))))
        );
        formCustomerInputPanelLayout.setVerticalGroup(
            formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                        .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                                .addComponent(namaCustomerInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formCustomerInputPanelLayout.createSequentialGroup()
                                .addComponent(namaCustomerInputLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaCustomerInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(actionButtonCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(namaCustomerInputLabel1)
                .addGap(18, 18, 18)
                .addGroup(formCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaCustomerInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        customerScrollPane.setOpaque(false);

        customerTextArea.setColumns(20);
        customerTextArea.setRows(5);
        customerScrollPane.setViewportView(customerTextArea);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerScrollPane)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonCustomerPanel;
    private javax.swing.JButton addCustomerInputButton;
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTextArea customerTextArea;
    private javax.swing.JButton deleteCustomerInputButton;
    private javax.swing.JButton editCustomerInputButton;
    private javax.swing.JPanel formCustomerInputPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaCustomerInputLabel;
    private javax.swing.JLabel namaCustomerInputLabel1;
    private javax.swing.JLabel namaCustomerInputLabel2;
    private javax.swing.JTextField namaCustomerInputTextField;
    private javax.swing.JTextField namaCustomerInputTextField1;
    private javax.swing.JTextField namaCustomerInputTextField2;
    private javax.swing.JButton saveCustomerButton;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JTextField searchCustomerInputTextField;
    private javax.swing.JPanel searchCustomerPanel;
    // End of variables declaration//GEN-END:variables
}
