package panelView;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import model.Rental;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class RentalMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public RentalMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchRentalPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        rentalLabel = new javax.swing.JLabel();
        searchRentalInputTextField = new javax.swing.JTextField();
        searchRentalButton = new javax.swing.JButton();
        formRentalInputPanel = new javax.swing.JPanel();
        judulFilmRentalInputTextField = new javax.swing.JTextField();
        judulFilmRentalInputLabel = new javax.swing.JLabel();
        customerRentalInputLabel = new javax.swing.JLabel();
        tanggalRentalInputLabel = new javax.swing.JLabel();
        actionButtonRentalPanel = new javax.swing.JPanel();
        addRentalInputButton = new javax.swing.JButton();
        deleteRentalInputButton = new javax.swing.JButton();
        editRentalInputButton = new javax.swing.JButton();
        saveRentalButton = new javax.swing.JButton();
        customerRentalDropdown = new javax.swing.JComboBox<>();
        tanggalSelesaiInputLabel = new javax.swing.JLabel();
        tanggalRentalDateChooser = new com.toedter.calendar.JDateChooser();
        tanggalKembaliRentalDateChooser = new com.toedter.calendar.JDateChooser();
        hargaSewaRentalInputLabel = new javax.swing.JLabel();
        hargaSewaRentalInputTextField = new javax.swing.JTextField();
        rentalScrollPane = new javax.swing.JScrollPane();
        rentalTable = new javax.swing.JTable();

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchRentalPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        rentalLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rentalLabel.setForeground(new java.awt.Color(255, 255, 255));
        rentalLabel.setText("RENTAL");

        searchRentalButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchRentalButton.setText("Search");

        javax.swing.GroupLayout searchRentalPanelLayout = new javax.swing.GroupLayout(searchRentalPanel);
        searchRentalPanel.setLayout(searchRentalPanelLayout);
        searchRentalPanelLayout.setHorizontalGroup(
            searchRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRentalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 713, Short.MAX_VALUE)
                .addComponent(searchRentalInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchRentalButton)
                .addGap(172, 172, 172))
            .addGroup(searchRentalPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(rentalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchRentalPanelLayout.setVerticalGroup(
            searchRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRentalPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchRentalButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(searchRentalInputTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalLabel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formRentalInputPanel.setOpaque(false);

        judulFilmRentalInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        judulFilmRentalInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        judulFilmRentalInputLabel.setText("Judul");

        customerRentalInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        customerRentalInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerRentalInputLabel.setText("Customer");

        tanggalRentalInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tanggalRentalInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        tanggalRentalInputLabel.setText("Tanggal Rental");

        actionButtonRentalPanel.setOpaque(false);

        addRentalInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addRentalInputButton.setText("ADD");

        deleteRentalInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        deleteRentalInputButton.setText("DELETE");

        editRentalInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        editRentalInputButton.setText("EDIT");

        javax.swing.GroupLayout actionButtonRentalPanelLayout = new javax.swing.GroupLayout(actionButtonRentalPanel);
        actionButtonRentalPanel.setLayout(actionButtonRentalPanelLayout);
        actionButtonRentalPanelLayout.setHorizontalGroup(
            actionButtonRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonRentalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRentalInputButton)
                .addGap(33, 33, 33)
                .addComponent(editRentalInputButton)
                .addGap(31, 31, 31)
                .addComponent(deleteRentalInputButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        actionButtonRentalPanelLayout.setVerticalGroup(
            actionButtonRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonRentalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actionButtonRentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRentalInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(editRentalInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteRentalInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        saveRentalButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveRentalButton.setText("SAVE");

        customerRentalDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        tanggalSelesaiInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tanggalSelesaiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        tanggalSelesaiInputLabel.setText("Tanggal Selesai");

        hargaSewaRentalInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        hargaSewaRentalInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        hargaSewaRentalInputLabel.setText("Harga Sewa");

        javax.swing.GroupLayout formRentalInputPanelLayout = new javax.swing.GroupLayout(formRentalInputPanel);
        formRentalInputPanel.setLayout(formRentalInputPanelLayout);
        formRentalInputPanelLayout.setHorizontalGroup(
            formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(customerRentalDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(judulFilmRentalInputLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(judulFilmRentalInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addComponent(customerRentalInputLabel))
                .addGap(31, 31, 31)
                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addComponent(tanggalSelesaiInputLabel)
                        .addContainerGap())
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                                .addComponent(tanggalKembaliRentalDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE))
                            .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalRentalInputLabel)
                                    .addComponent(tanggalRentalDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hargaSewaRentalInputLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hargaSewaRentalInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)))
                        .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRentalInputPanelLayout.createSequentialGroup()
                                .addComponent(actionButtonRentalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRentalInputPanelLayout.createSequentialGroup()
                                .addComponent(saveRentalButton)
                                .addGap(273, 273, 273))))))
        );
        formRentalInputPanelLayout.setVerticalGroup(
            formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                            .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                                    .addComponent(judulFilmRentalInputLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(judulFilmRentalInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                                    .addComponent(tanggalRentalInputLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tanggalRentalDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRentalInputPanelLayout.createSequentialGroup()
                            .addComponent(actionButtonRentalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addComponent(hargaSewaRentalInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaSewaRentalInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerRentalInputLabel)
                    .addComponent(tanggalSelesaiInputLabel))
                .addGroup(formRentalInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(saveRentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerRentalDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formRentalInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalKembaliRentalDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        rentalScrollPane.setOpaque(false);

        rentalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rentalScrollPane.setViewportView(rentalTable);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchRentalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formRentalInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rentalScrollPane)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchRentalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formRentalInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonRentalPanel;
    private javax.swing.JButton addRentalInputButton;
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JComboBox<String> customerRentalDropdown;
    private javax.swing.JLabel customerRentalInputLabel;
    private javax.swing.JButton deleteRentalInputButton;
    private javax.swing.JButton editRentalInputButton;
    private javax.swing.JPanel formRentalInputPanel;
    private javax.swing.JLabel hargaSewaRentalInputLabel;
    private javax.swing.JTextField hargaSewaRentalInputTextField;
    private javax.swing.JLabel judulFilmRentalInputLabel;
    private javax.swing.JTextField judulFilmRentalInputTextField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel rentalLabel;
    private javax.swing.JScrollPane rentalScrollPane;
    private javax.swing.JTable rentalTable;
    private javax.swing.JButton saveRentalButton;
    private javax.swing.JButton searchRentalButton;
    private javax.swing.JTextField searchRentalInputTextField;
    private javax.swing.JPanel searchRentalPanel;
    private com.toedter.calendar.JDateChooser tanggalKembaliRentalDateChooser;
    private com.toedter.calendar.JDateChooser tanggalRentalDateChooser;
    private javax.swing.JLabel tanggalRentalInputLabel;
    private javax.swing.JLabel tanggalSelesaiInputLabel;
    // End of variables declaration//GEN-END:variables
}
