package panelView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class StafMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public StafMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchStafPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        stafLabel = new javax.swing.JLabel();
        searchStafInputTextField = new javax.swing.JTextField();
        searchStafButton = new javax.swing.JButton();
        formStafInputPanel = new javax.swing.JPanel();
        namaStafInputTextField = new javax.swing.JTextField();
        namaStafInputLabel = new javax.swing.JLabel();
        actionButtonStafPanel = new javax.swing.JPanel();
        addStafInputButton = new javax.swing.JButton();
        deleteStafInputButton = new javax.swing.JButton();
        editStafInputButton = new javax.swing.JButton();
        saveStafButton = new javax.swing.JButton();
        stafScrollPane = new javax.swing.JScrollPane();
        stafTextArea = new javax.swing.JTextArea();

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchStafPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        stafLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        stafLabel.setForeground(new java.awt.Color(255, 255, 255));
        stafLabel.setText("STAF");

        searchStafButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchStafButton.setText("Search");

        javax.swing.GroupLayout searchStafPanelLayout = new javax.swing.GroupLayout(searchStafPanel);
        searchStafPanel.setLayout(searchStafPanelLayout);
        searchStafPanelLayout.setHorizontalGroup(
            searchStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStafPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(searchStafInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchStafButton)
                .addGap(172, 172, 172))
            .addGroup(searchStafPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(stafLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchStafPanelLayout.setVerticalGroup(
            searchStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStafPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchStafButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(searchStafInputTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stafLabel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formStafInputPanel.setOpaque(false);

        namaStafInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        namaStafInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaStafInputLabel.setText("Nama ");

        actionButtonStafPanel.setOpaque(false);

        addStafInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addStafInputButton.setText("ADD");

        deleteStafInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        deleteStafInputButton.setText("DELETE");

        editStafInputButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        editStafInputButton.setText("EDIT");
        editStafInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStafInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionButtonStafPanelLayout = new javax.swing.GroupLayout(actionButtonStafPanel);
        actionButtonStafPanel.setLayout(actionButtonStafPanelLayout);
        actionButtonStafPanelLayout.setHorizontalGroup(
            actionButtonStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonStafPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStafInputButton)
                .addGap(33, 33, 33)
                .addComponent(editStafInputButton)
                .addGap(31, 31, 31)
                .addComponent(deleteStafInputButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        actionButtonStafPanelLayout.setVerticalGroup(
            actionButtonStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonStafPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actionButtonStafPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStafInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(editStafInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStafInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        saveStafButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveStafButton.setText("SAVE");

        javax.swing.GroupLayout formStafInputPanelLayout = new javax.swing.GroupLayout(formStafInputPanel);
        formStafInputPanel.setLayout(formStafInputPanelLayout);
        formStafInputPanelLayout.setHorizontalGroup(
            formStafInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formStafInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formStafInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formStafInputPanelLayout.createSequentialGroup()
                        .addGroup(formStafInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaStafInputLabel)
                            .addComponent(namaStafInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actionButtonStafPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(formStafInputPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveStafButton)
                        .addGap(273, 273, 273))))
        );
        formStafInputPanelLayout.setVerticalGroup(
            formStafInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formStafInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formStafInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formStafInputPanelLayout.createSequentialGroup()
                        .addComponent(namaStafInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaStafInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formStafInputPanelLayout.createSequentialGroup()
                        .addComponent(actionButtonStafPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addComponent(saveStafButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        stafScrollPane.setOpaque(false);

        stafTextArea.setColumns(20);
        stafTextArea.setRows(5);
        stafScrollPane.setViewportView(stafTextArea);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchStafPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formStafInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stafScrollPane)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchStafPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formStafInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stafScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editStafInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStafInputButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStafInputButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonStafPanel;
    private javax.swing.JButton addStafInputButton;
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JButton deleteStafInputButton;
    private javax.swing.JButton editStafInputButton;
    private javax.swing.JPanel formStafInputPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaStafInputLabel;
    private javax.swing.JTextField namaStafInputTextField;
    private javax.swing.JButton saveStafButton;
    private javax.swing.JButton searchStafButton;
    private javax.swing.JTextField searchStafInputTextField;
    private javax.swing.JPanel searchStafPanel;
    private javax.swing.JLabel stafLabel;
    private javax.swing.JScrollPane stafScrollPane;
    private javax.swing.JTextArea stafTextArea;
    // End of variables declaration//GEN-END:variables
}
