package panelView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lucas Manuel SB
 */
public class TransaksiMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public TransaksiMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pembayaranButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        colorGradientBiarBagus1 = new view.ColorGradientBiarBagus();
        searchTransaksiPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        transaksiLabel = new javax.swing.JLabel();
        searchTrasaksiInputTextField = new javax.swing.JTextField();
        searchTransaksiButton = new javax.swing.JButton();
        formTransaksiInputPanel = new javax.swing.JPanel();
        idRentalTransaksiInputLabel = new javax.swing.JLabel();
        stafTransaksiInputLabel = new javax.swing.JLabel();
        totalHargaTransaksiInputLabel = new javax.swing.JLabel();
        totalHargaTransaksiInputTextField = new javax.swing.JTextField();
        saveTransaksiButton = new javax.swing.JButton();
        idRentalTransaksiComboBox = new javax.swing.JComboBox<>();
        stafTransaksiComboBox = new javax.swing.JComboBox<>();
        metodePembayaranTransaksiInputLabel = new javax.swing.JLabel();
        tunaiTransaksiRadioButton = new javax.swing.JRadioButton();
        qrisTransaksiRadioButton = new javax.swing.JRadioButton();
        transaksiScrollPane = new javax.swing.JScrollPane();
        transaksiTextArea = new javax.swing.JTextArea();

        colorGradientBiarBagus1.setColorEnd(new java.awt.Color(0, 0, 0));
        colorGradientBiarBagus1.setColorStart(new java.awt.Color(255, 0, 0));

        searchTransaksiPanel.setOpaque(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main logo (1).png"))); // NOI18N
        logoLabel.setText(".");

        transaksiLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setText("TRANSAKSI");

        searchTransaksiButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchTransaksiButton.setText("Search");

        javax.swing.GroupLayout searchTransaksiPanelLayout = new javax.swing.GroupLayout(searchTransaksiPanel);
        searchTransaksiPanel.setLayout(searchTransaksiPanelLayout);
        searchTransaksiPanelLayout.setHorizontalGroup(
            searchTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(searchTrasaksiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchTransaksiButton)
                .addGap(172, 172, 172))
            .addGroup(searchTransaksiPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(transaksiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchTransaksiPanelLayout.setVerticalGroup(
            searchTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransaksiPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(searchTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchTransaksiButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(searchTrasaksiInputTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiLabel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        formTransaksiInputPanel.setOpaque(false);

        idRentalTransaksiInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        idRentalTransaksiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        idRentalTransaksiInputLabel.setText("ID Rental");

        stafTransaksiInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        stafTransaksiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        stafTransaksiInputLabel.setText("Staf ");

        totalHargaTransaksiInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        totalHargaTransaksiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalHargaTransaksiInputLabel.setText("Total Harga");

        saveTransaksiButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveTransaksiButton.setText("SAVE");

        idRentalTransaksiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idRentalTransaksiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRentalTransaksiComboBoxActionPerformed(evt);
            }
        });

        stafTransaksiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stafTransaksiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stafTransaksiComboBoxActionPerformed(evt);
            }
        });

        metodePembayaranTransaksiInputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        metodePembayaranTransaksiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        metodePembayaranTransaksiInputLabel.setText("Metode Pembayaran");

        pembayaranButtonGroup.add(tunaiTransaksiRadioButton);
        tunaiTransaksiRadioButton.setText("Tunai");

        pembayaranButtonGroup.add(qrisTransaksiRadioButton);
        qrisTransaksiRadioButton.setText("QRIS");
        qrisTransaksiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisTransaksiRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formTransaksiInputPanelLayout = new javax.swing.GroupLayout(formTransaksiInputPanel);
        formTransaksiInputPanel.setLayout(formTransaksiInputPanelLayout);
        formTransaksiInputPanelLayout.setHorizontalGroup(
            formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                            .addComponent(idRentalTransaksiInputLabel)
                            .addGap(219, 219, 219))
                        .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                            .addComponent(idRentalTransaksiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(31, 31, 31)))
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addComponent(stafTransaksiInputLabel)
                        .addGap(244, 244, 244))
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addComponent(stafTransaksiComboBox, 0, 284, Short.MAX_VALUE)
                        .addGap(31, 31, 31)))
                .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalHargaTransaksiInputLabel)
                            .addComponent(totalHargaTransaksiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 660, Short.MAX_VALUE))
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                                .addComponent(tunaiTransaksiRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(qrisTransaksiRadioButton))
                            .addComponent(metodePembayaranTransaksiInputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveTransaksiButton)
                        .addGap(324, 324, 324))))
        );
        formTransaksiInputPanelLayout.setVerticalGroup(
            formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addComponent(idRentalTransaksiInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idRentalTransaksiComboBox))
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addComponent(totalHargaTransaksiInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalHargaTransaksiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formTransaksiInputPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stafTransaksiInputLabel)
                            .addComponent(metodePembayaranTransaksiInputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stafTransaksiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tunaiTransaksiRadioButton)
                            .addComponent(qrisTransaksiRadioButton))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTransaksiInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        transaksiScrollPane.setOpaque(false);

        transaksiTextArea.setColumns(20);
        transaksiTextArea.setRows(5);
        transaksiScrollPane.setViewportView(transaksiTextArea);

        javax.swing.GroupLayout colorGradientBiarBagus1Layout = new javax.swing.GroupLayout(colorGradientBiarBagus1);
        colorGradientBiarBagus1.setLayout(colorGradientBiarBagus1Layout);
        colorGradientBiarBagus1Layout.setHorizontalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchTransaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formTransaksiInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaksiScrollPane)
        );
        colorGradientBiarBagus1Layout.setVerticalGroup(
            colorGradientBiarBagus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorGradientBiarBagus1Layout.createSequentialGroup()
                .addComponent(searchTransaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formTransaksiInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transaksiScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorGradientBiarBagus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void qrisTransaksiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisTransaksiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qrisTransaksiRadioButtonActionPerformed

    private void stafTransaksiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stafTransaksiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stafTransaksiComboBoxActionPerformed

    private void idRentalTransaksiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRentalTransaksiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRentalTransaksiComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.ColorGradientBiarBagus colorGradientBiarBagus1;
    private javax.swing.JPanel formTransaksiInputPanel;
    private javax.swing.JComboBox<String> idRentalTransaksiComboBox;
    private javax.swing.JLabel idRentalTransaksiInputLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel metodePembayaranTransaksiInputLabel;
    private javax.swing.ButtonGroup pembayaranButtonGroup;
    private javax.swing.JRadioButton qrisTransaksiRadioButton;
    private javax.swing.JButton saveTransaksiButton;
    private javax.swing.JButton searchTransaksiButton;
    private javax.swing.JPanel searchTransaksiPanel;
    private javax.swing.JTextField searchTrasaksiInputTextField;
    private javax.swing.JComboBox<String> stafTransaksiComboBox;
    private javax.swing.JLabel stafTransaksiInputLabel;
    private javax.swing.JLabel totalHargaTransaksiInputLabel;
    private javax.swing.JTextField totalHargaTransaksiInputTextField;
    private javax.swing.JLabel transaksiLabel;
    private javax.swing.JScrollPane transaksiScrollPane;
    private javax.swing.JTextArea transaksiTextArea;
    private javax.swing.JRadioButton tunaiTransaksiRadioButton;
    // End of variables declaration//GEN-END:variables
}
